### ISSUE TITLE
Display metadata

### ISSUE THREAD

**Issue by adamhathcock** [codedread/kthoom#18]
Maybe a window for comicbook.xml files inside the archive.

Found some discussion here: https://github.com/Tenma-Server/Tenma/issues/32

**Comment by codedread** [comment]
Sounds like from https://code.google.com/archive/p/comicbookinfo/ that they are proposing stuffing the metadata xml into the zip file comment field which we throw away here:

https://github.com/codedread/kthoom/blob/master/code/bitjs/archive/unzip.js#L598

**Comment by adamhathcock** [comment]
There are probably several standards.  Using an xml file that was just in the archive used to be what’s ComicRack used

**Comment by codedread** [comment]
@adamhathcock - I've started thinking about this now, but I need some examples of comic books that have book the comicinfo.xml file [1] and ones that have the comicbookinfo metadata embedded in the zip file comment [2].

By any chance, do you have some good examples of this?


[1] https://github.com/ciromattia/kcc/wiki/ComicRack-metadata
[2] https://code.google.com/archive/p/comicbookinfo/

**Comment by codedread** [comment]
Implementation-wise, I think a drawer on the right to mirror the Reading Stack drawer on the left. Icon-wise, it can be a "tag".

**Comment by codedread** [comment]
Basic metadata viewer tray added. Please file additional bugs and make it better (I have very few books with metadata!)
