### ISSUE TITLE
How to enable google drive?

### ISSUE THREAD

**Issue by AlexKaboem** [codedread/kthoom#44]
I realize this is probably not the best place to post a beginners question, but I couldn’t find a better way to contact the developers of this great script - my apologies!
 
I'm trying to integrate Kthoom in my comic book related website. Works fine, only in the menu is the ‘open from Google drive’ field missing. Pressing 'G' also doesn't do anything.

Obviously I’m missing something - I guess I need some api thing from Google - but I can not find more information on the net.

So if someone would be so friendly to point me in the right direction? I have to confess that my knowledge of coding is almost zero (but I’m an expert in copy/paste)

Thanks a lot,
Alex

**Comment by codedread** [comment]
This is kind of a big topic :-)

https://codedread.com/kthoom/ => press G here (or choose Open > Open from Google Drive) and it will try to bring up a popup. Allow the popup, approve that Kthoom can access your Google Drive, then it should work on this website.

For your own integration / installation of kthoom on your own website, you will need to look into kthoom-google.js

https://github.com/codedread/kthoom/blob/master/code/kthoom-google.js#L241

  * You will need to create a Google Cloud project and enable the Google Drive APIs.
  * In https://console.cloud.google.com/apis/credentials, create a web client and authorizes your domain.
  * The kthoom-google.js script tries to fetch a gkey.json file from your website that must include your apiKey and clientId

HTH!

**Comment by AlexKaboem** [comment]
Thanks a lot, it is working now! (in case other people try to do the same: also enable the picker api otherwise Google will say that the API developer key is invalid.)

I still have a few questions. My site is about European comics, which can sometimes be very big (200-300+ mb), so loading and unzipping them can take some time - especially if you have older hardware and a slow connection.

Mostly, people will load them from an external site through the 'open from url' option.  Right now, the progress bar will start working when you open the link, stops  during the download, and resume working during unzipping. In some cases, this can take a few minutes and in this period, it looks like the browser is frozen. Would you consider to fix this in a future update? (similar as in [issue 33](https://github.com/codedread/kthoom/issues/33))

About [issue #12](https://github.com/codedread/kthoom/issues/12) - progressive page loading: I completely agree that it would seriously speed up things for big files. I also understand your concerns about the first page not being the first page in the zip. Must be some cultural thing, but I never seen a European book where the files are not stored in the right order ;-) (every book I tested on https://comic-book-reader.com/ loads fine - and they start showing pages while unzipping is still in progress). 

In your reply on this issue you say that it is easy to change by removing the sorting inside Kthoom. Do you mind to whisper in my ear what exactly to remove so I can test? If not working I will revert to the original file of course.

Thanks a lot!
Alex

**Comment by codedread** [comment]
Ok, how about this - I'll tell you the secret if you do me a favor :)

https://github.com/codedread/kthoom/blob/97e19c91b1c55d685f0c7e0d4a174394eeb6fc97/code/comic-book-binder.js#L49

If the optimizedForStreaming_ bit is true here, then as files are extracted they are added to the book and rendered immediately. This makes such a huge difference when streaming a file that I added my own attribute to the comicinfo.xml format as described here: https://github.com/codedread/kthoom/issues/12#issuecomment-592980610

I don't expect others to go out there and necessarily add or update a comicinfo.xml file for every comic book archive file they have though.

So now for my request: Send me a patch that adds a URL request parameter to always enable "optimizedForStreaming" mode, (i.e. ?optimizedForStreaming=1) or something.  All URL params are serialized to the Params object in helpers.js.

Feel free to ignore my request if you don't know JavaScript very well! :)

**Comment by AlexKaboem** [comment]
I know absolutely nothing about js and still wonder what I'm doing on a site for coders ;-) I run a wp site and all I normally do is glue some plugins together - mostly this works fine lol.

Serious now: adding/changing a comicinfo.xml file is a great idea, but not very practical as I wil need to do this with 50-60.000 comics.... My wife will kill me ;-)

But I wonder if the following would be possible.

A book consist of a number of .jpg files, and normally the cover of the book is something like xxx000.jpg or xxx001.jpg - so the first file in a long row.

Would it be possible to write something like:

[if the filename of the first picture (contains 0.jpg OR contains 1.jpg)] then it is optimizedForStreaming ELSE it is not.

If this check could be done you won't need a comicinfo.xml file (I think). Of course there are always exceptions, but if it works for 90% of the books, it would be a great improvement.

Jezus, really need to learn to program by myself ;-(

PS: I messed  a bit with the code so that most of the books I tried were marked as 'optimizedforstreaming'. To my surprise I also had too many errors... Guess there is some problem with the unrar algorithm (all my books are cbr btw). But the books loaded much faster as before ;-)

**Comment by codedread** [comment]
Ok, I think i can work on this myself, I'll let you know when it's ready. If you could clarify what errors are happening, that part confused me (are you saying that some of your cbr files no longer open if you set optimizedForStreaming to true?

**Comment by codedread** [comment]
Ok, I put in something that (hopefully) will help you. Just include alwaysOptimizedForStreaming=true in your URL and it should always try to do that.

**Comment by codedread** [comment]
Please reopen this bug if this doesn't work!
