### ISSUE TITLE
support PDF

### ISSUE THREAD

**Issue by lolhangman** [codedread/kthoom#45]
please support PDF files

**Comment by codedread** [comment]
Browsers do this already natively - can you expand on what you're looking for in the reader for this?

**Comment by lolhangman** [comment]
Sorry in fact i am interested in viewing files stored on the webserver

**Comment by codedread** [comment]
I still didn't understand, sorry! A browser can open a PDF from a web server on its own without needing kthoom, for example: https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/pdf_reference_1-7.pdf

So what I'm trying to understand is what kthoom would bring to the experience that the browser doesn't already support.

Thanks!

**Comment by lolhangman** [comment]
Yes you are right i misunderstood the purpose of the project.
This open comics on client side and what i need is something opening comics stored on the server and sending to client page by page.
Sorry for the request which is not relevant

**Comment by codedread** [comment]
Sure np - fwiw, it should be relatively easy to write a server program that will unzip/unrar cbr/cbz files and feed to the browser page-by-page, since that's how comic book formats have the data internally. What is much harder would be PDFs.  Good luck!
